import { View, Text } from 'react-native'
import React, { createContext,useEffect,useState } from 'react'
import AsyncStorage from '@react-native-async-storage/async-storage';


const AppContext = createContext()

const AppProvider = ({children})=>{
    const [isLoggedIn,setIsLoggedIn] = useState(true)
    const [user,setUser] = useState(null)
    const [isLoading,setIsLoading] = useState(true)
    const [CurrentCategory,setCurrentCategory] = useState('SUV')
    const [detailsIndex,setDetailsIndex] = useState(0)


    useEffect(()=>{
        const saveLogInStatus = async (params) => {
            try {
                await AsyncStorage.setItem('@logInStatus:key',JSON.stringify(isLoggedIn)) 
                console.log(JSON.stringify(isLoggedIn))
            } catch (error) {
                console.log(error)
            } 
        }
        saveLogInStatus()

    }, [isLoggedIn])
    

    useEffect(()=>{
        const retrieveData = async ()=>{
            try {
                const logInStorage = await AsyncStorage.getItem('@logInStatus:key',)
                if (logInStorage != null){
                    setIsLoggedIn(JSON.parse(logInStorage))
                    console.log('loginVal',logInStorage)
                }
                
            } catch (error) {
                console.log(error)
            }
        }
        retrieveData()
    },[])


    const [form,setForm] = useState({
        userName : '',
        email:'',
        password:'',
    })

    const [carCategories,setCarCategories]= useState([
        
        {
            name: 'SUV',
            path: require('../assets/images/Car categories/SUV.jpeg'
)
        },
        {
            name: 'Luxury Cars',
            path: require('../assets/images/Car categories/Luxury.jpeg')

        },

        {
            name: 'Compact Cars',
            path: require('../assets/images/Car categories/Compact.jpg')

        },
        
        {
            name: 'Electric Cars',
            path: require('../assets/images/Car categories/electric-cars.webp')

        },
        {
            name: 'Pickup Trucks',
            path: require('../assets/images/Car categories/Pickup.jpeg'
)
        },
        {
            name: 'Sports Cars',
            path: require('../assets/images/Car categories/SportCar.jpeg')

        },
        {
            name: 'Convertibles',
            path: require('../assets/images/Car categories/convertible.jpg'
)
        },
        
        {
            name: 'Vans',
            path: require('../assets/images/Car categories/Vans.jpg')

        },

        {
            name: 'Economy',
            path: require('../assets/images/Car categories/Economy.jpg')
        },
        {
            name: 'Off-Road Vehicles',
            path: require('../assets/images/Car categories/Offroad.jpeg')

        },
        {
            name: 'Limousines',
            path: require('../assets/images/Car categories/Limo.jpeg')

        },
        {
            name: 'Mini Buses',
            path: require('../assets/images/Car categories/Minibus.jpg')

        },
        
        
        

    ])
    const [carListings,setCarListings]= useState([
        {
            id:0,
            name: 'Honda CR-V',
            path: 'https://th.bing.com/th/id/OIF.KmWIq8D8D0kZ1Z2z5np7pA?w=282&h=187&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 13000,
            category: 'Compact Cars',
            state: 'Port Harcourt',
            country: 'Nigeria',
            manufactureYear: '2021',
            trending: false,
            description: 'The Honda CR-V is spacious, efficient, and perfect for all kinds of adventures.',
            acceleration: '0-60 mph in 8.2 seconds',
            engineSize: '1.5L Turbo 4-cylinder',
            electric: false,
            horsePower: '190 hp',
            profileName: 'PH Adventures',
            reviewScore: 4.7,
            comments: [
                'Spacious and great for road trips!',
                'Handled well even on rough roads.',
            ],
            yearsOnApp: 3
        },
        {
            id:1,
            name: "Nissan Rogue",
            path: "https://th.bing.com/th/id/OIF.Db7Cuz1YoJZ74lGFU52W4A?w=326&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7",
            rentalPricePerDay: 14000,
            category: "Compact Cars",
            state: "Lagos",
            country: "Nigeria",
            manufactureYear: "2022",
            trending: false,
            description: "Hey there! I’m renting out my beloved 2022 Nissan Rogue. This compact crossover SUV is perfect for both city driving and long trips. It has a stylish design and a comfortable interior that can easily fit your family or friends. The advanced safety features give you peace of mind on the road. With a smooth ride and ample cargo space, it’s great for weekend getaways or daily commutes. Plus, it’s got a powerful 2.5L 4-cylinder engine with 181 hp, so you’ll have plenty of power when you need it. The acceleration is pretty impressive too, going from 0-60 mph in just 8.2 seconds. Whether you’re running errands around Lagos or heading out on a road trip, this car won’t disappoint!",
            acceleration: "0-60 mph in 8.2 seconds",
            engineSize: "2.5L 4-cylinder",
            electric: false,
            horsePower: "181 hp",
            profileName: "Adebola",
            reviewStore: 4.5,        
            comments: ["Great car!", "Loved the ride"], 
            yearsSpent: 1            
        },
        {   
            id:2,
            name: "Toyota Camry",
            path: "https://th.bing.com/th/id/R.36b32737244f30c481071a2a2a6448b0?rik=fZMG%2beReZXNz4g&pid=ImgRaw&r=0",
            rentalPricePerDay: 12000,
            category: "Sedan",
            state: "Abuja",
            country: "Nigeria",
            manufactureYear: "2023",
            trending: false,
            description: "Experience luxury and reliability with this 2023 Toyota Camry. Features a smooth-running 2.5L engine, spacious interior, and excellent fuel economy. Perfect for business trips or family outings. The car comes with advanced safety features and modern entertainment system.",
            acceleration: "0-60 mph in 7.5 seconds",
            engineSize: "2.5L 4-cylinder",
            electric: false,
            horsePower: "203 hp",
            profileName: "Chiamaka", 
            reviewStore: 4.7,          
            comments: ["Very comfortable!", "Smooth ride"], 
            yearsSpent: 2              
        },
        {   
            id:3,
            name: "Tesla Model 3",
            path: "https://cdn.motor1.com/images/mgl/qpGBL/s1/tesla-model-3-gray-2.jpg",
            rentalPricePerDay: 25000,
            category: "Electric Cars",
            state: "Lagos",
            country: "Nigeria",
            manufactureYear: "2023",
            trending: false,
            description: "Step into the future with this all-electric Tesla Model 3. Featuring cutting-edge technology, autopilot capabilities, and instant acceleration. The minimalist interior and large touchscreen provide a modern driving experience. Perfect for tech enthusiasts and environmentally conscious drivers.",
            acceleration: "0-60 mph in 3.1 seconds",
            engineSize: "Electric Motor",
            electric: true,
            horsePower: "283 hp",
            profileName: "Kwame", 
            reviewStore: 4.9,         
            comments: ["Amazing tech!", "Very fast"], 
            yearsSpent: 3             
        },
        {
            id:4,
            name: "Toyota Camry",
            path: "https://th.bing.com/th/id/OIP.QbIM5PClZZKpwmZttCKKSAHaE6?w=1600&h=1063&rs=1&pid=ImgDetMain",
            rentalPricePerDay: 12000,
            category: "Sedan",
            state: "Lagos",
            country: "Nigeria",
            manufactureYear: "2021",
            trending: false,
            description: "This 2021 Toyota Camry is a reliable and stylish sedan, perfect for both city driving and long trips. It features a comfortable interior, advanced safety features, and a smooth ride. With a powerful engine and impressive fuel efficiency, it’s a great choice for any journey.",
            acceleration: "0-60 mph in 7.6 seconds",
            engineSize: "2.5L 4-cylinder",
            electric: false,
            horsePower: "203 hp",
            profileName: "Ngozi", 
            reviewStore: 4.6,        
            comments: ["Great fuel efficiency", "Smooth ride"], 
            yearsSpent: 1            
        },
        {   

            id:5,
            name: "Honda Accord",
            path: "https://th.bing.com/th/id/OIP.q7nXtPQPhmvRcpdRl3qytwHaEK?rs=1&pid=ImgDetMain",
            rentalPricePerDay: 13000,
            category: "Sedan",
            state: "Abuja",
            country: "Nigeria",
            manufactureYear: "2022",
            trending: false,
            description: "The 2022 Honda Accord is a top choice for a midsize sedan. It offers a spacious and comfortable interior, advanced technology, and excellent fuel efficiency. With a powerful engine and smooth handling, it’s perfect for both daily commutes and long road trips.",
            acceleration: "0-60 mph in 7.2 seconds",
            engineSize: "1.5L turbocharged 4-cylinder",
            electric: false,
            horsePower: "192 hp",
            profileName: "Abiola", 
            reviewStore: 4.8,            
            comments: ["Very spacious", "Excellent handling"], 
            yearsSpent: 2                
        },
        
        {
            id:6,
            name: 'Ford Explorer',
            path: 'https://th.bing.com/th/id/R.948083b9bd48a78dab85111387e1ff77?rik=k8plslpaNZ8QXw&riu=http%3a%2f%2fcdn.carbuzz.com%2fgallery-images%2f1600%2f712000%2f0%2f712094.jpg&ehk=LE1S8fqJBg1b%2fOZu5NCpnmx652%2bWXQVo%2f0dL8fQBsz8%3d&risl=&pid=ImgRaw&r=0',
            rentalPricePerDay: 18000,
            category: 'SUV',
            state: 'Lagos',
            country: 'Nigeria',
            manufactureYear: '2021',
            trending: true,
            description: 'The 2021 Ford Explorer is a versatile and spacious SUV, ideal for family trips and outdoor adventures. It features a powerful engine, advanced safety features, and a comfortable interior with plenty of cargo space. Whether you’re exploring the city or the countryside, this SUV has you covered.',
            acceleration: '0-60 mph in 6.8 seconds',
            engineSize: '2.3L turbocharged 4-cylinder',
            electric: false,
            horsePower: '300 hp',
            profileName: 'Ifeanyi',
            reviewStore: 4.6,
            comments: ['Spacious and comfortable', 'Perfect for trips'],
            yearsSpent: 3
        },
        {
            id:7,
            name: 'Chevrolet Malibu',
            path: 'https://th.bing.com/th/id/R.a2318780ca15231a9079c6c17a327355?rik=aQyTyypzdm7gZQ&riu=http%3a%2f%2fwww.automoblog.net%2fwp-content%2fuploads%2f2011%2f12%2f2013-Chevrolet-Malibu-Eco-070.jpg&ehk=kSwLpFp8wvN%2b3NtpQH%2bVGy5%2f186yxR1WTWl1F67e9Ac%3d&risl=&pid=ImgRaw&r=0',
            rentalPricePerDay: 11000,
            category: 'Sedan',
            state: 'Port Harcourt',
            country: 'Nigeria',
            manufactureYear: '2020',
            trending: false,
            description: 'The 2020 Chevrolet Malibu is a stylish and efficient sedan, perfect for both city driving and long trips. It offers a comfortable interior, advanced technology, and impressive fuel efficiency. With a smooth ride and powerful engine, it’s a great choice for any journey.',
            acceleration: '0-60 mph in 8.0 seconds',
            engineSize: '1.5L turbocharged 4-cylinder',
            electric: false,
            horsePower: '160 hp',
            profileName: 'Adewale',
            reviewStore: 4.5,
            comments: ['Stylish and efficient', 'Great fuel economy'],
            yearsSpent: 2
        },
        {   
            id:8,
            name: 'BMW X5',
            path: 'https://th.bing.com/th/id/R.a8eea639ecbbf86ebe877002931dece5?rik=fsYqO7vzy%2bgW0A&riu=http%3a%2f%2fwww.hdcarwallpapers.com%2fwalls%2f2015_bmw_x5_m-wide.jpg&ehk=gjmSxO00woacwrzIWcBxdtPR59cXVRa2ThgW2QoJlBY%3d&risl=&pid=ImgRaw&r=0',
            rentalPricePerDay: 25000,
            category: 'SUV',
            state: 'Lagos',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: true,
            description: 'The 2022 BMW X5 is a luxury SUV that combines performance, comfort, and advanced technology. It features a powerful engine, spacious interior, and cutting-edge safety features. Whether you’re driving in the city or on the highway, this SUV offers a premium driving experience.',
            acceleration: '0-60 mph in 5.3 seconds',
            engineSize: '3.0L turbocharged 6-cylinder',
            electric: false,
            horsePower: '335 hp',
            profileName: 'Kofi',
            reviewStore: 4.9,
            comments: ['Luxurious and powerful', 'High-end features'],
            yearsSpent: 3
        },
        {
            id:9,
            name: 'Mercedes-Benz C-Class',
            path: 'https://th.bing.com/th/id/R.938720b581bf50f9f2d694dbf149a0f2?rik=6oQe3FRdrFNbeQ&pid=ImgRaw&r=0',
            rentalPricePerDay: 22000,
            category: 'Sedan',
            state: 'Lagos',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: true,
            description: 'The 2022 Mercedes-Benz C-Class is a luxury sedan that offers a perfect blend of performance, comfort, and advanced technology. It features a powerful engine, a luxurious interior, and cutting-edge safety features. Whether you’re driving in the city or on the highway, this sedan provides a premium driving experience.',
            acceleration: '0-60 mph in 5.7 seconds',
            engineSize: '2.0L turbocharged 4-cylinder',
            electric: false,
            horsePower: '255 hp',
            profileName: 'Oluwaseun',
            reviewStore: 4.8,
            comments: ['Luxurious ride', 'Top-notch features'],
            yearsSpent: 2
        },
        {
            id:10,
            name: 'Audi Q5',
            path: 'https://th.bing.com/th/id/OIF.E6j3PMIarVRgdmfJosVcaA?rs=1&pid=ImgDetMain',
            rentalPricePerDay: 20000,
            category: 'Luxury Cars',
            state: 'Abuja',
            country: 'Nigeria',
            manufactureYear: '2021',
            trending: false,
            description: 'The 2021 Audi Q5 is a luxury SUV that combines performance, comfort, and advanced technology. It features a powerful engine, a spacious interior, and cutting-edge safety features. Whether you’re driving in the city or on the highway, this SUV offers a premium driving experience.',
            acceleration: '0-60 mph in 5.9 seconds',
            engineSize: '2.0L turbocharged 4-cylinder',
            electric: false,
            horsePower: '261 hp',
            profileName: 'Bongani',
            reviewStore: 4.7,
            comments: ['Comfortable and high-tech', 'Smooth ride'],
            yearsSpent: 2
        },
        
        {
            id:11,
            name: 'Hyundai Tucson',
            path: 'https://www.thecarexpert.co.uk/wp-content/uploads/2023/07/Hyundai-Tucson-test-drive-front-action-1200x800.jpg',
            rentalPricePerDay: 15000,
            category: 'Compact Cars',
            state: 'Port Harcourt',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: false,
            description: 'The 2022 Hyundai Tucson is a compact SUV that offers a stylish design, a comfortable interior, and advanced safety features. It features a powerful engine, a smooth ride, and ample cargo space, making it a great choice for city driving and long trips.',
            acceleration: '0-60 mph in 8.8 seconds',
            engineSize: '2.5L 4-cylinder',
            electric: false,
            horsePower: '187 hp',
            profileName: 'Chidinma',
            reviewStore: 4.7,
            comments: ['Stylish and comfortable', 'Great for city driving'],
            yearsSpent: 2
        },
        {
            id:12,
            name: 'Kia Sportage',
            path: 'https://images.carexpert.com.au/resize/3000/-/app/uploads/2022/01/2022-Kia-Sportage-S-2.0D-AWD-HERO.jpg',
            rentalPricePerDay: 14000,
            category: 'Compact Cars',
            state: 'Lagos',
            country: 'Nigeria',
            manufactureYear: '2021',
            trending: false,
            description: 'The 2021 Kia Sportage is a compact SUV that offers a stylish design, a comfortable interior, and advanced safety features. It features a powerful engine, a smooth ride, and ample cargo space, making it a great choice for city driving and long trips.',
            acceleration: '0-60 mph in 8.6 seconds',
            engineSize: '2.4L 4-cylinder',
            electric: false,
            horsePower: '181 hp',
            profileName: 'Tolu',
            reviewStore: 4.6,
            comments: ['Comfortable and reliable', 'Perfect for trips'],
            yearsSpent: 1
        },
        {
            id:13,
            name: 'Mazda CX-5',
            path: 'https://th.bing.com/th/id/OIP.Yn_ivv63RG7Sa41PbguOwAHaE8?rs=1&pid=ImgDetMain',
            rentalPricePerDay: 16000,
            category: 'SUV',
            state: 'Abuja',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: false,
            description: 'The 2022 Mazda CX-5 is a compact SUV that offers a stylish design, a comfortable interior, and advanced safety features. It features a powerful engine, a smooth ride, and ample cargo space, making it a great choice for city driving and long trips.',
            acceleration: '0-60 mph in 7.9 seconds',
            engineSize: '2.5L 4-cylinder',
            electric: false,
            horsePower: '187 hp',
            profileName: 'Yemi',
            reviewStore: 4.8,
            comments: ['Smooth ride', 'Spacious interior'],
            yearsSpent: 2
        },
        {
            id:14,
            name: 'Toyota RAV4',
            path: 'https://th.bing.com/th?id=OIF.DBDGFbYAWjMQ8u1%2bfCPJOw&rs=1&pid=ImgDetMain',
            rentalPricePerDay: 17000,
            category: 'SUV',
            state: 'Lagos',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: false,
            description: 'The 2022 Toyota RAV4 is a versatile and reliable compact SUV. It offers a comfortable interior, advanced safety features, and a smooth ride. With a powerful engine and ample cargo space, it’s perfect for both city driving and long trips.',
            acceleration: '0-60 mph in 8.0 seconds',
            engineSize: '2.5L 4-cylinder',
            electric: false,
            horsePower: '203 hp',
            profileName: 'Binta',
            reviewStore: 4.9,
            comments: ['Versatile and reliable', 'Great for long trips'],
            yearsSpent: 3
        },
        
        {
            id:15,
            name: 'Nissan Altima',
            path: 'https://th.bing.com/th/id/R.ed26ea58e0411af1f8728f9ecc1dd9a8?rik=3S9RhH3GvVD%2faQ&pid=ImgRaw&r=0',
            rentalPricePerDay: 13000,
            category: 'Sedan',
            state: 'Abuja',
            country: 'Nigeria',
            manufactureYear: '2021',
            trending: true,
            description: 'The 2021 Nissan Altima is a stylish and efficient sedan. It features a comfortable interior, advanced technology, and impressive fuel efficiency. With a smooth ride and powerful engine, it’s a great choice for any journey.',
            acceleration: '0-60 mph in 7.4 seconds',
            engineSize: '2.5L 4-cylinder',
            electric: false,
            horsePower: '188 hp',
            profileName: 'Amina',
            reviewStore: 4.5,
            comments: ['Stylish and efficient', 'Comfortable ride'],
            yearsSpent: 2
        },
        {
            id:16,
            name: 'Jeep Grand Cherokee',
            path: 'https://th.bing.com/th/id/R.a2d46ade27847a72768bb783bc900080?rik=MsSedAZXh2dcDQ&riu=http%3a%2f%2f3.bp.blogspot.com%2f-GG8AUJMv6NU%2fTg5zbcXihXI%2fAAAAAAAAAfU%2f_ERPJurvaPU%2fs1600%2f96_jeep_grandcherokee_laredo_1.jpg&ehk=PHAsDRbGDGO9SQfmyrEriMS558cF%2bZkKp8gem7N%2f4%2fU%3d&risl=&pid=ImgRaw&r=0',
            rentalPricePerDay: 20000,
            category: 'SUV',
            state: 'Lagos',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: false,
            description: 'The 2022 Jeep Grand Cherokee is a rugged and capable SUV. It offers a spacious interior, advanced safety features, and a powerful engine. Whether you’re exploring the city or heading off-road, this SUV is ready for any adventure.',
            acceleration: '0-60 mph in 7.0 seconds',
            engineSize: '3.6L V6',
            electric: false,
            horsePower: '293 hp',
            profileName: 'Babajide',
            reviewStore: 4.7,
            comments: ['Rugged and spacious', 'Great for adventures'],
            yearsSpent: 3
        },
        {
            id:17,
            name: 'Volkswagen Passat',
            path: 'https://th.bing.com/th/id/OIP.RbMrO29zYGsz-RisWsvepgHaFj?rs=1&pid=ImgDetMain',
            rentalPricePerDay: 12000,
            category: 'Sedan',
            state: 'Port Harcourt',
            country: 'Nigeria',
            manufactureYear: '2020',
            trending: false,
            description: 'The 2020 Volkswagen Passat is a stylish and efficient sedan. It features a comfortable interior, advanced technology, and impressive fuel efficiency. With a smooth ride and powerful engine, it’s a great choice for any journey.',
            acceleration: '0-60 mph in 7.8 seconds',
            engineSize: '2.0L turbocharged 4-cylinder',
            electric: false,
            horsePower: '174 hp',
            profileName: 'Chukwuemeka',
            reviewStore: 4.6,
            comments: ['Stylish and comfortable', 'Great for city driving'],
            yearsSpent: 2
        },
        {   
            id:18,
            name: 'Subaru Outback',
            path: 'https://th.bing.com/th?id=OIF.wHp5jEdl%2f27vUDuygglCgw&rs=1&pid=ImgDetMain',
            rentalPricePerDay: 16000,
            category: 'SUV',
            state: 'Abuja',
            country: 'Nigeria',
            manufactureYear: '2021',
            trending: true,
            description: 'The 2021 Subaru Outback is a versatile and reliable SUV. It offers a comfortable interior, advanced safety features, and a smooth ride. With a powerful engine and ample cargo space, it’s perfect for both city driving and long trips.',
            acceleration: '0-60 mph in 8.5 seconds',
            engineSize: '2.5L 4-cylinder',
            electric: false,
            horsePower: '182 hp',
            profileName: 'Funke',
            reviewStore: 4.8,
            comments: ['Reliable and versatile', 'Spacious interior'],
            yearsSpent: 3
        },
        
        {   
            id:19,
            name: 'Toyota RAV4',
            path: 'https://th.bing.com/th/id/OIP.PjEEpTUmWTYHQfrV12DTAgHaEK?w=301&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 17000,
            category: 'Compact Cars',
            state: 'Lagos',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: false,
            description: 'Hey there! I’m renting out my 2022 Toyota RAV4. This compact SUV is perfect for both city driving and long trips. It has a comfortable interior, advanced safety features, and a smooth ride. With a powerful engine and ample cargo space, it’s great for weekend getaways or daily commutes. Whether you’re running errands around Lagos or heading out on a road trip, this car won’t disappoint!',
            acceleration: '0-60 mph in 8.0 seconds',
            engineSize: '2.5L 4-cylinder',
            electric: false,
            horsePower: '203 hp',
            profileName: 'Binta',
            reviewStore: 4.9,
            comments: ['Versatile and reliable', 'Great for long trips'],
            yearsSpent: 3
        },
        {
            id:20,
            name: 'Nissan Altima',
            path: 'https://th.bing.com/th/id/OIP.7SbqWOBBGvH4co-ezB3ZqAHaEK?w=275&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 13000,
            category: 'Sedan',
            state: 'Abuja',
            country: 'Nigeria',
            manufactureYear: '2021',
            trending: false,
            description: 'I’m renting out my 2021 Nissan Altima. This stylish and efficient sedan is perfect for any journey. It features a comfortable interior, advanced technology, and impressive fuel efficiency. With a smooth ride and powerful engine, it’s great for both city driving and long trips. You’ll love how it handles on the road!',
            acceleration: '0-60 mph in 7.4 seconds',
            engineSize: '2.5L 4-cylinder',
            electric: false,
            horsePower: '188 hp',
            profileName: 'Amina',
            reviewStore: 4.5,
            comments: ['Stylish and efficient', 'Comfortable ride'],
            yearsSpent: 2
        },
        {
            id:21,
            name: 'Jeep Grand Cherokee',
            path: 'https://th.bing.com/th/id/OIP.2ZBwMRIoxE61B09xTuFn5QHaEo?w=307&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 20000,
            category: 'SUV',
            state: 'Lagos',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: true,
            description: 'Check out my 2022 Jeep Grand Cherokee! This rugged and capable SUV is ready for any adventure. It offers a spacious interior, advanced safety features, and a powerful engine. Whether you’re exploring the city or heading off-road, this SUV has you covered. Perfect for family trips or outdoor adventures!',
            acceleration: '0-60 mph in 7.0 seconds',
            engineSize: '3.6L V6',
            electric: false,
            horsePower: '293 hp',
            profileName: 'Babajide',
            reviewStore: 4.7,
            comments: ['Rugged and spacious', 'Great for adventures'],
            yearsSpent: 3
        },
        {
            id:22,
            name: 'Volkswagen Passat',
            path: 'https://th.bing.com/th/id/OIP.UwL6lNb3pDPB01v7aeK2CwHaE8?w=268&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 12000,
            category: 'Sedan',
            state: 'Port Harcourt',
            country: 'Nigeria',
            manufactureYear: '2020',
            trending: true,
            description: 'I’m renting out my 2020 Volkswagen Passat. This stylish and efficient sedan is perfect for both city driving and long trips. It features a comfortable interior, advanced technology, and impressive fuel efficiency. With a smooth ride and powerful engine, it’s a great choice for any journey. You’ll love driving it!',
            acceleration: '0-60 mph in 7.8 seconds',
            engineSize: '2.0L turbocharged 4-cylinder',
            electric: false,
            horsePower: '174 hp',
            profileName: 'Chukwuemeka',
            reviewStore: 4.6,
            comments: ['Stylish and comfortable', 'Great for city driving'],
            yearsSpent: 2
        },
        
        {
            id:23,
            name: 'Subaru Outback',
            path: 'https://th.bing.com/th?id=OIF.E0W%2fpKWaM2h%2fdspyTr%2bCYw&w=267&h=200&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 16000,
            category: 'SUV',
            state: 'Abuja',
            country: 'Nigeria',
            manufactureYear: '2021',
            trending: false,
            description: 'I’m renting out my 2021 Subaru Outback. This versatile and reliable SUV is perfect for both city driving and long trips. It offers a comfortable interior, advanced safety features, and a smooth ride. With a powerful engine and ample cargo space, it’s great for weekend getaways or daily commutes. You’ll enjoy every moment behind the wheel!',
            acceleration: '0-60 mph in 8.5 seconds',
            engineSize: '2.5L 4-cylinder',
            electric: false,
            horsePower: '182 hp',
            profileName: 'Funke',
            reviewStore: 4.8,
            comments: ['Reliable and versatile', 'Spacious interior'],
            yearsSpent: 3
        },
        {
            id:24,
            name: 'Ford Escape',
            path: 'https://th.bing.com/th/id/OIP.qO9V6D0VA9NmljOiCqdkrgHaE5?w=277&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 15000,
            category: 'Compact Cars',
            state: 'Lagos',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: false,
            description: 'I’m renting out my 2022 Ford Escape. This compact SUV is perfect for both city driving and long trips. It has a comfortable interior, advanced safety features, and a smooth ride. With a powerful engine and ample cargo space, it’s great for weekend getaways or daily commutes. You’ll love how it handles on the road!',
            acceleration: '0-60 mph in 7.7 seconds',
            engineSize: '2.0L turbocharged 4-cylinder',
            electric: false,
            horsePower: '250 hp',
            profileName: 'Nkem',
            reviewStore: 4.7,
            comments: ['Comfortable and powerful', 'Great for city driving'],
            yearsSpent: 2
        },
        {
            id:25,
            name: 'Chevrolet Equinox',
            path: 'https://th.bing.com/th/id/OIP.ZiLRN3aj-qaExgRsgmESHwHaFj?w=236&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 14000,
            category: 'Compact Cars',
            state: 'Abuja',
            country: 'Nigeria',
            manufactureYear: '2021',
            trending: false,
            description: 'I’m renting out my 2021 Chevrolet Equinox. This compact SUV is perfect for both city driving and long trips. It features a comfortable interior, advanced safety features, and a smooth ride. With a powerful engine and ample cargo space, it’s great for weekend getaways or daily commutes. You’ll enjoy every moment behind the wheel!',
            acceleration: '0-60 mph in 8.5 seconds',
            engineSize: '1.5L turbocharged 4-cylinder',
            electric: false,
            horsePower: '170 hp',
            profileName: 'Ifeoma',
            reviewStore: 4.5,
            comments: ['Comfortable and reliable', 'Perfect for trips'],
            yearsSpent: 2
        },
        {
            id:26,
            name: 'Hyundai Santa Fe',
            path: 'https://th.bing.com/th/id/OIP.tbKfFJxFfmJ5udCcjl4-fQHaEL?w=251&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 16000,
            category: 'SUV',
            state: 'Port Harcourt',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: false,
            description: 'I’m renting out my 2022 Hyundai Santa Fe. This SUV is perfect for both city driving and long trips. It has a comfortable interior, advanced safety features, and a smooth ride. With a powerful engine and ample cargo space, it’s great for weekend getaways or daily commutes. You’ll love how it handles on the road!',
            acceleration: '0-60 mph in 7.8 seconds',
            engineSize: '2.5L 4-cylinder',
            electric: false,
            horsePower: '191 hp',
            profileName: 'Adewale',
            reviewStore: 4.7,
            comments: ['Smooth ride', 'Spacious interior'],
            yearsSpent: 3
        },
        {
            id:27,
            name: 'Kia Sorento',
            path: 'https://th.bing.com/th/id/OIF.ndjYo2qRsY1hyOHeYTDFwQ?w=326&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 17000,
            category: 'SUV',
            state: 'Lagos',
            country: 'Nigeria',
            manufactureYear: '2021',
            trending: false,
            description: 'I’m renting out my 2021 Kia Sorento. This SUV is perfect for both city driving and long trips. It features a comfortable interior, advanced safety features, and a smooth ride. With a powerful engine and ample cargo space, it’s great for weekend getaways or daily commutes. You’ll enjoy every moment behind the wheel!',
            acceleration: '0-60 mph in 7.5 seconds',
            engineSize: '2.5L turbocharged 4-cylinder',
            electric: false,
            horsePower: '281 hp',
            profileName: 'Oluwaseun',
            reviewStore: 4.6,
            comments: ['Comfortable and powerful', 'Great for long trips'],
            yearsSpent: 2
        },
        {
            id:28,
            name: 'Mazda CX-9',
            path: 'https://th.bing.com/th/id/OIP.lvZ8vqM7n489jSgT_YtBqAHaEK?w=243&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 18000,
            category: 'SUV',
            state: 'Abuja',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: false,
            description: 'I’m renting out my 2022 Mazda CX-9. This SUV is perfect for both city driving and long trips. It has a comfortable interior, advanced safety features, and a smooth ride. With a powerful engine and ample cargo space, it’s great for weekend getaways or daily commutes. You’ll love how it handles on the road!',
            acceleration: '0-60 mph in 7.1 seconds',
            engineSize: '2.5L turbocharged 4-cylinder',
            electric: false,
            horsePower: '250 hp',
            profileName: 'Chidi',
            reviewStore: 4.7,
            comments: ['Smooth ride', 'Spacious interior'],
            yearsSpent: 3
        },
        {
            id:29,
            name: 'Ford Escape',
            path: 'https://th.bing.com/th/id/OIP.idf_YlgWWwSNf69lom_fxQHaE6?w=254&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 15000,
            category: 'Compact Cars',
            state: 'Lagos',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: false,
            description: 'I’m renting out my 2022 Ford Escape. This compact SUV is perfect for both city driving and long trips. It has a comfortable interior, advanced safety features, and a smooth ride. With a powerful engine and ample cargo space, it’s great for weekend getaways or daily commutes. You’ll love how it handles on the road!',
            acceleration: '0-60 mph in 7.7 seconds',
            engineSize: '2.0L turbocharged 4-cylinder',
            electric: false,
            horsePower: '250 hp',
            profileName: 'Nkem',
            reviewStore: 4.7,
            comments: ['Comfortable and powerful', 'Great for city driving'],
            yearsSpent: 2
        },
        {
            id:30,
            name: 'Chevrolet Equinox',
            path: 'https://th.bing.com/th/id/OIP.ME6YJRcX8ap-n-3KZjJ0LQHaEh?w=260&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 14000,
            category: 'Compact Cars',
            state: 'Abuja',
            country: 'Nigeria',
            manufactureYear: '2021',
            trending: true,
            description: 'I’m renting out my 2021 Chevrolet Equinox. This compact SUV is perfect for both city driving and long trips. It features a comfortable interior, advanced safety features, and a smooth ride. With a powerful engine and ample cargo space, it’s great for weekend getaways or daily commutes. You’ll enjoy every moment behind the wheel!',
            acceleration: '0-60 mph in 8.5 seconds',
            engineSize: '1.5L turbocharged 4-cylinder',
            electric: false,
            horsePower: '170 hp',
            profileName: 'Ifeoma',
            reviewStore: 4.5,
            comments: ['Comfortable and reliable', 'Perfect for trips'],
            yearsSpent: 2
        },
        {
            id:31,
            name: 'Hyundai Santa Fe',
            path: 'https://th.bing.com/th/id/OIP.0dC75GjEZu6W7vRZnDeBSgHaEK?w=307&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 16000,
            category: 'SUV',
            state: 'Port Harcourt',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: false,
            description: 'I’m renting out my 2022 Hyundai Santa Fe. This SUV is perfect for both city driving and long trips. It has a comfortable interior, advanced safety features, and a smooth ride. With a powerful engine and ample cargo space, it’s great for weekend getaways or daily commutes. You’ll love how it handles on the road!',
            acceleration: '0-60 mph in 7.8 seconds',
            engineSize: '2.5L 4-cylinder',
            electric: false,
            horsePower: '191 hp',
            profileName: 'Adewale',
            reviewStore: 4.7,
            comments: ['Smooth ride', 'Spacious interior'],
            yearsSpent: 3
        },
        {
            id:32,
            name: 'Mazda CX-9',
            path: 'https://th.bing.com/th/id/OIP.lvZ8vqM7n489jSgT_YtBqAHaEK?w=243&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 18000,
            category: 'SUV',
            state: 'Abuja',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: false,
            description: 'I’m renting out my 2022 Mazda CX-9. This SUV is perfect for both city driving and long trips. It has a comfortable interior, advanced safety features, and a smooth ride. With a powerful engine and ample cargo space, it’s great for weekend getaways or daily commutes. You’ll love how it handles on the road!',
            acceleration: '0-60 mph in 7.1 seconds',
            engineSize: '2.5L turbocharged 4-cylinder',
            electric: false,
            horsePower: '250 hp',
            profileName: 'Chidi',
            reviewStore: 4.7,
            comments: ['Smooth ride', 'Spacious interior'],
            yearsSpent: 3
        },
        {
            id:33,
            name: 'Honda CR-V',
            path: 'https://th.bing.com/th/id/R.d6c5581b1e4e8d51c5b204ac5c3bb211?rik=70LGgYTahdtJgQ&pid=ImgRaw&r=0',
            rentalPricePerDay: 16000,
            category: 'Compact Cars',
            state: 'Lagos',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: false,
            description: 'I’m renting out my 2022 Honda CR-V. This compact SUV is perfect for both city driving and long trips. It has a comfortable interior, advanced safety features, and a smooth ride. With a powerful engine and ample cargo space, it’s great for weekend getaways or daily commutes. You’ll love how it handles on the road!',
            acceleration: '0-60 mph in 7.5 seconds',
            engineSize: '1.5L turbocharged 4-cylinder',
            electric: false,
            horsePower: '190 hp',
            profileName: 'Adaobi',
            reviewStore: 4.6,
            comments: ['Comfortable and reliable', 'Great for city driving'],
            yearsSpent: 2
        },
        {
            id:34,
            name: 'Toyota Highlander',
            path: 'https://th.bing.com/th/id/OIP.wKynKdgatvT9ePgYydk54wHaE7?w=274&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 18000,
            category: 'SUV',
            state: 'Abuja',
            country: 'Nigeria',
            manufactureYear: '2021',
            trending: false,
            description: 'I’m renting out my 2021 Toyota Highlander. This SUV is perfect for both city driving and long trips. It features a comfortable interior, advanced safety features, and a smooth ride. With a powerful engine and ample cargo space, it’s great for weekend getaways or daily commutes. You’ll enjoy every moment behind the wheel!',
            acceleration: '0-60 mph in 7.2 seconds',
            engineSize: '3.5L V6',
            electric: false,
            horsePower: '295 hp',
            profileName: 'Kelechi',
            reviewStore: 4.8,
            comments: ['Powerful and comfortable', 'Great for long trips'],
            yearsSpent: 3
        },
        {
            id:35,
            name: 'Ford Edge',
            path: 'https://th.bing.com/th/id/OIP.nOBLZcG8teybEThlnKVQ6gHaE9?w=301&h=201&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 17000,
            category: 'SUV',
            state: 'Port Harcourt',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: false,
            description: 'I’m renting out my 2022 Ford Edge. This SUV is perfect for both city driving and long trips. It has a comfortable interior, advanced safety features, and a smooth ride. With a powerful engine and ample cargo space, it’s great for weekend getaways or daily commutes. You’ll love how it handles on the road!',
            acceleration: '0-60 mph in 6.8 seconds',
            engineSize: '2.7L turbocharged V6',
            electric: false,
            horsePower: '335 hp',
            profileName: 'Emeka',
            reviewStore: 4.7,
            comments: ['Powerful and smooth', 'Great for city driving'],
            yearsSpent: 2
        },
        {
            id:36,
            name: 'Chevrolet Traverse',
            path: 'https://th.bing.com/th/id/OIP._WaAkZnSJqbQaOSXxER9SwHaFj?w=219&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 19000,
            category: 'SUV',
            state: 'Lagos',
            country: 'Nigeria',
            manufactureYear: '2021',
            trending: false,
            description: 'I’m renting out my 2021 Chevrolet Traverse. This SUV is perfect for both city driving and long trips. It features a comfortable interior, advanced safety features, and a smooth ride. With a powerful engine and ample cargo space, it’s great for weekend getaways or daily commutes. You’ll enjoy every moment behind the wheel!',
            acceleration: '0-60 mph in 6.9 seconds',
            engineSize: '3.6L V6',
            electric: false,
            horsePower: '310 hp',
            profileName: 'Bayo',
            reviewStore: 4.6,
            comments: ['Spacious and comfortable', 'Great for long trips'],
            yearsSpent: 3
        },
        {
            id:37,
            name: 'Jeep Wrangler',
            path: 'https://th.bing.com/th/id/OIP.MrWr3842imxMo9q0Ab01XwHaE6?w=202&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 20000,
            category: 'SUV',
            state: 'Abuja',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: false,
            description: 'I’m renting out my 2022 Jeep Wrangler. This rugged and capable SUV is ready for any adventure. It offers a spacious interior, advanced safety features, and a powerful engine. Whether you’re exploring the city or heading off-road, this SUV has you covered. Perfect for family trips or outdoor adventures!',
            acceleration: '0-60 mph in 6.1 seconds',
            engineSize: '3.6L V6',
            electric: false,
            horsePower: '285 hp',
            profileName: 'Gbenga',
            reviewStore: 4.9,
            comments: ['Rugged and powerful', 'Great for adventures'],
            yearsSpent: 3
        },
        
        {
            id:38,
            name: 'Honda CR-V',
            path: 'https://th.bing.com/th/id/OIP.w6pFtolt1wVyOyRBVSWEKwHaEv?w=236&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 16000,
            category: 'Compact Cars',
            state: 'Lagos',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: false,
            description: 'I’m renting out my 2022 Honda CR-V. This compact SUV is perfect for both city driving and long trips. It has a comfortable interior, advanced safety features, and a smooth ride. With a powerful engine and ample cargo space, it’s great for weekend getaways or daily commutes. You’ll love how it handles on the road!',
            acceleration: '0-60 mph in 7.5 seconds',
            engineSize: '1.5L turbocharged 4-cylinder',
            electric: false,
            horsePower: '190 hp',
            profileName: 'Adaobi',
            reviewStore: 4.6,
            comments: ['Comfortable and reliable', 'Great for city driving'],
            yearsSpent: 2
        },
        {   
            id:39,
            name: 'Toyota Highlander',
            path: 'https://th.bing.com/th/id/OIP.wKynKdgatvT9ePgYydk54wHaE7?w=274&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 18000,
            category: 'SUV',
            state: 'Abuja',
            country: 'Nigeria',
            manufactureYear: '2021',
            trending: true,
            description: 'I’m renting out my 2021 Toyota Highlander. This SUV is perfect for both city driving and long trips. It features a comfortable interior, advanced safety features, and a smooth ride. With a powerful engine and ample cargo space, it’s great for weekend getaways or daily commutes. You’ll enjoy every moment behind the wheel!',
            acceleration: '0-60 mph in 7.2 seconds',
            engineSize: '3.5L V6',
            electric: false,
            horsePower: '295 hp',
            profileName: 'Kelechi',
            reviewStore: 4.8,
            comments: ['Powerful and comfortable', 'Great for long trips'],
            yearsSpent: 3
        },
        {
            id:40,
            name: 'Ford Edge',
            path: 'https://th.bing.com/th/id/OIP.ZxJSdABFk-8qphYuNQtqCQHaEK?w=255&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 17000,
            category: 'SUV',
            state: 'Port Harcourt',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: false,
            description: 'I’m renting out my 2022 Ford Edge. This SUV is perfect for both city driving and long trips. It has a comfortable interior, advanced safety features, and a smooth ride. With a powerful engine and ample cargo space, it’s great for weekend getaways or daily commutes. You’ll love how it handles on the road!',
            acceleration: '0-60 mph in 6.8 seconds',
            engineSize: '2.7L turbocharged V6',
            electric: false,
            horsePower: '335 hp',
            profileName: 'Emeka',
            reviewStore: 4.7,
            comments: ['Powerful and smooth', 'Great for city driving'],
            yearsSpent: 2
        },
        {
            id:41,
            name: 'Chevrolet Traverse',
            path: 'https://th.bing.com/th/id/OIP.oqnd_gXlv8kgPDXYsFN0pAHaFj?w=225&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 19000,
            category: 'SUV',
            state: 'Lagos',
            country: 'Nigeria',
            manufactureYear: '2021',
            trending: false,
            description: 'I’m renting out my 2021 Chevrolet Traverse. This SUV is perfect for both city driving and long trips. It features a comfortable interior, advanced safety features, and a smooth ride. With a powerful engine and ample cargo space, it’s great for weekend getaways or daily commutes. You’ll enjoy every moment behind the wheel!',
            acceleration: '0-60 mph in 6.9 seconds',
            engineSize: '3.6L V6',
            electric: false,
            horsePower: '310 hp',
            profileName: 'Bayo',
            reviewStore: 4.6,
            comments: ['Spacious and comfortable', 'Great for long trips'],
            yearsSpent: 3
        },
        {
            id:42,
            name: 'Jeep Wrangler',
            path: 'https://th.bing.com/th/id/OIP.2I1dAjj1Ld_J3WjW6i1n7wHaEc?w=291&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 20000,
            category: 'SUV',
            state: 'Abuja',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: false,
            description: 'I’m renting out my 2022 Jeep Wrangler. This rugged and capable SUV is ready for any adventure. It offers a spacious interior, advanced safety features, and a powerful engine. Whether you’re exploring the city or heading off-road, this SUV has you covered. Perfect for family trips or outdoor adventures!',
            acceleration: '0-60 mph in 6.1 seconds',
            engineSize: '3.6L V6',
            electric: false,
            horsePower: '285 hp',
            profileName: 'Gbenga',
            reviewStore: 4.9,
            comments: ['Rugged and powerful', 'Great for adventures'],
            yearsSpent: 3
        },
        {   
            id:43,
            name: 'Nissan Murano',
            path: 'https://th.bing.com/th/id/OIP.l3eku-hcRv6TYZ_YiuTOUAHaEK?w=290&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 18000,
            category: 'SUV',
            state: 'Lagos',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: false,
            description: 'I’m renting out my 2022 Nissan Murano. This stylish and comfortable SUV is perfect for both city driving and long trips. It features a spacious interior, advanced safety features, and a smooth ride. With a powerful engine and ample cargo space, it’s great for weekend getaways or daily commutes. You’ll love how it handles on the road!',
            acceleration: '0-60 mph in 7.3 seconds',
            engineSize: '3.5L V6',
            electric: false,
            horsePower: '260 hp',
            profileName: 'Chinelo',
            reviewStore: 4.8,
            comments: ['Stylish and comfortable', 'Great for long trips'],
            yearsSpent: 2
        },
        
        {   
            id:44,
            name: 'Toyota Corolla',
            path: 'https://th.bing.com/th/id/OIP.EHgzuFfwOniySwFkYaYwNwHaE8?w=250&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 13000,
            category: 'Compact Cars',
            state: 'Abuja',
            country: 'Nigeria',
            manufactureYear: '2021',
            trending: false,
            description: 'Reliable and fuel-efficient, the 2021 Toyota Corolla is a great option for city drives and commutes. With a sleek design and comfortable seating, it’s perfect for small families or solo travelers.',
            acceleration: '0-60 mph in 9.0 seconds',
            engineSize: '1.8L 4-cylinder',
            electric: false,
            horsePower: '139 hp',
            profileName: 'Fatima',
            reviewStore: 4.4,
            comments: ['Fuel-efficient', 'Comfortable seating'],
            yearsSpent: 1
        },
        {
            id:45,
            name: 'Honda Civic',
            path: 'https://th.bing.com/th/id/OIP.gfFUO9hsaeXVQxm8KepafQAAAA?w=335&h=181&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 12000,
            category: 'Compact Cars',
            state: 'Ibadan',
            country: 'Nigeria',
            manufactureYear: '2020',
            trending: false,
            description: 'The 2020 Honda Civic offers a sporty look and an engaging drive. Ideal for both leisure trips and daily commutes, this car stands out with its reliability and sleek performance.',
            acceleration: '0-60 mph in 7.8 seconds',
            engineSize: '2.0L 4-cylinder',
            electric: false,
            horsePower: '158 hp',
            profileName: 'Oluwatosin',
            reviewStore: 4.6,
            comments: ['Sporty and reliable', 'Engaging drive'],
            yearsSpent: 2
        },
        {
            id:46,
            name: 'Ford Escape',
            path: 'https://th.bing.com/th/id/OIP.i7cfAy2jux2PnSJF0jQLGgHaEo?w=296&h=184&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 15000,
            category: 'SUV',
            state: 'Kano',
            country: 'Nigeria',
            manufactureYear: '2023',
            trending: false,
            description: 'Enjoy the 2023 Ford Escape, a versatile SUV built for adventure. With spacious seating and a dynamic performance, it’s great for both families and travelers.',
            acceleration: '0-60 mph in 7.5 seconds',
            engineSize: '2.0L EcoBoost 4-cylinder',
            electric: false,
            horsePower: '250 hp',
            profileName: 'Amina',
            reviewStore: 4.5,
            comments: ['Versatile and spacious', 'Great performance'],
            yearsSpent: 1
        },
        {
            id:47,
            name: 'Chevrolet Equinox',
            path: 'https://th.bing.com/th/id/OIP.vtdArPqFHX37bFBh-tRJjQHaEA?w=314&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 16000,
            category: 'SUV',
            state: 'Port Harcourt',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: false,
            description: 'Experience comfort and power with the 2022 Chevrolet Equinox. Perfect for family trips and long drives, it offers ample space and a smooth ride.',
            acceleration: '0-60 mph in 7.9 seconds',
            engineSize: '1.5L Turbo 4-cylinder',
            electric: false,
            horsePower: '170 hp',
            profileName: 'Chidiebere',
            reviewStore: 4.7,
            comments: ['Comfortable and spacious', 'Smooth ride'],
            yearsSpent: 2
        },
        {   
            id:48,
            name: 'Tesla Model 3',
            path: 'https://th.bing.com/th/id/OIP.SrTktqaFgifHftTCqxA2HgHaEK?w=302&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 20000,
            category: 'Electric Cars',
            state: 'Lagos',
            country: 'Nigeria',
            manufactureYear: '2023',
            trending: false,
            description: 'The 2023 Tesla Model 3 is a game-changer for electric vehicles. With cutting-edge technology and a luxurious interior, this car provides an unparalleled driving experience.',
            acceleration: '0-60 mph in 5.3 seconds',
            engineSize: 'Electric Motor',
            electric: true,
            horsePower: '283 hp',
            profileName: 'Adebayo',
            reviewStore: 4.9,
            comments: ['Cutting-edge technology', 'Luxurious interior'],
            yearsSpent: 1
        },
        {   
            id:49,
            name: 'Hyundai Elantra',
            path: 'https://th.bing.com/th/id/R.a848b04d748489594aa4879e7199d267?rik=P5kgsSy6LdbNBQ&riu=http%3a%2f%2fwww.blogcdn.com%2fwww.autoblog.com%2fmedia%2f2010%2f12%2f01-2011-hyundai-elantra-fd.jpg&ehk=fgoUddaOwrh7bzB4zy0LRYoOpPB4Bdm36XsJyeUv%2b3I%3d&risl=&pid=ImgRaw&r=0',
            rentalPricePerDay: 12500,
            category: 'Compact Cars',
            state: 'Abuja',
            country: 'Nigeria',
            manufactureYear: '2021',
            trending: false,
            description: 'The 2021 Hyundai Elantra combines style and efficiency. It’s a reliable sedan that is perfect for everyday use.',
            acceleration: '0-60 mph in 8.5 seconds',
            engineSize: '2.0L 4-cylinder',
            electric: false,
            horsePower: '147 hp',
            profileName: 'Zainab',
            reviewStore: 4.6,
            comments: ['Stylish and efficient', 'Reliable sedan'],
            yearsSpent: 1
        },
        {
            id:50,
            name: 'BMW X5',
            path: 'https://th.bing.com/th/id/OIP.91-q12dUjM4tNYbVbusD1QHaEn?w=264&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 25000,
            category: 'Luxury Cars',
            state: 'Lagos',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: false,
            description: 'Luxury meets performance with the 2022 BMW X5. This SUV offers a premium driving experience with a powerful engine and upscale features.',
            acceleration: '0-60 mph in 5.3 seconds',
            engineSize: '3.0L Turbo 6-cylinder',
            electric: false,
            horsePower: '335 hp',
            profileName: 'Ikenna',
            reviewStore: 4.8,
            comments: ['Luxury and performance', 'Powerful engine'],
            yearsSpent: 2
        },
        {
            id:51,
            name: 'Mercedes-Benz C-Class',
            path: 'https://th.bing.com/th/id/OIP.32T_e0u8CFtxUW-aZgD3LwHaD4?w=324&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 30000,
            category: 'Luxury Cars',
            state: 'Kano',
            country: 'Nigeria',
            manufactureYear: '2023',
            trending: false,
            description: 'The 2023 Mercedes-Benz C-Class defines sophistication and elegance. It’s the ideal choice for those seeking luxury and cutting-edge technology.',
            acceleration: '0-60 mph in 5.6 seconds',
            engineSize: '2.0L Turbo 4-cylinder',
            electric: false,
            horsePower: '255 hp',
            profileName: 'Bashir',
            reviewStore: 4.9,
            comments: ['Sophisticated and elegant', 'Cutting-edge technology'],
            yearsSpent: 1
        },
        {   
            id:52,
            name: 'Kia Sportage',
            path: 'https://th.bing.com/th/id/OIP.0-MNSY0FrsPXhpWqOcpnbAHaFj?w=183&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 14000,
            category: 'SUV',
            state: 'Port Harcourt',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: false,
            description: 'The 2022 Kia Sportage is a reliable and practical SUV for all your adventures. It offers comfort, safety, and versatility.',
            acceleration: '0-60 mph in 8.1 seconds',
            engineSize: '2.4L 4-cylinder',
            electric: false,
            horsePower: '181 hp',
            profileName: 'Ndidi',
            reviewStore: 4.6,
            comments: ['Reliable and practical', 'Versatile'],
            yearsSpent: 2
        },
        {
            id:53,
            name: 'Mazda CX-5',
            path: 'https://th.bing.com/th/id/OIP.5J6nqiP5v3W0_Qyn54hxQwHaE8?w=220&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 14500,
            category: 'SUV',
            state: 'Enugu',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: false,
            description: 'The 2022 Mazda CX-5 delivers exceptional performance and refined styling. Perfect for both city commutes and off-road adventures, this SUV combines power with comfort.',
            acceleration: '0-60 mph in 7.5 seconds',
            engineSize: '2.5L 4-cylinder',
            electric: false,
            horsePower: '187 hp',
            profileName: 'Nkechi',
            reviewStore: 4.7,
            comments: ['Exceptional performance', 'Refined styling'],
            yearsSpent: 2
        },
        {
            id:54,
            name: 'Volkswagen Golf',
            path: 'https://th.bing.com/th/id/OIP.DhGOntyn4LY7YKJKWXz_7wHaEA?w=272&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 11000,
            category: 'Compact Cars',
            state: 'Lagos',
            country: 'Nigeria',
            manufactureYear: '2021',
            trending: false,
            description: 'The 2021 Volkswagen Golf is a versatile hatchback, known for its reliability and comfortable ride. Ideal for everyday use and short trips.',
            acceleration: '0-60 mph in 8.2 seconds',
            engineSize: '1.4L Turbo 4-cylinder',
            electric: false,
            horsePower: '147 hp',
            profileName: 'Bolanle',
            reviewStore: 4.4,
            comments: ['Versatile and reliable', 'Comfortable ride'],
            yearsSpent: 1
        },
        {
            id:55,
            name: 'Subaru Outback',
            path: 'https://th.bing.com/th/id/OIF.OULsfG7tJM0cqiIksoJAMA?w=278&h=186&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 17000,
            category: 'SUV',
            state: 'Jos',
            country: 'Nigeria',
            manufactureYear: '2023',
            trending: false,
            description: 'The 2023 Subaru Outback is the ultimate adventure companion. With standard all-wheel drive and plenty of cargo space, it’s ready for any journey.',
            acceleration: '0-60 mph in 8.7 seconds',
            engineSize: '2.4L Turbo 4-cylinder',
            electric: false,
            horsePower: '260 hp',
            profileName: 'Yakubu',
            reviewStore: 4.8,
            comments: ['Ultimate adventure companion', 'Ready for any journey'],
            yearsSpent: 2
        },
        {
            id:56,
            name: 'Audi A4',
            path: 'https://th.bing.com/th/id/OIP.o8xP7QMGHeJ9Y0I7HGs77QHaEK?w=303&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 22000,
            category: 'Luxury Cars',
            state: 'Abuja',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: true,
            description: 'The 2022 Audi A4 is a luxury sedan that offers a blend of elegance and performance. Perfect for business trips or stylish city driving.',
            acceleration: '0-60 mph in 6.3 seconds',
            engineSize: '2.0L Turbo 4-cylinder',
            electric: false,
            horsePower: '201 hp',
            profileName: 'Salihu',
            reviewStore: 4.9,
            comments: ['Elegant and high-performance', 'Ideal for business trips'],
            yearsSpent: 2
        },
        {
            id:57,
            name: 'Jeep Wrangler',
            path: 'https://th.bing.com/th?id=OIF.w%2fku%2f6mfTOsoO3NWd%2bhxiA&w=274&h=183&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 25000,
            category: 'SUV',
            state: 'Kaduna',
            country: 'Nigeria',
            manufactureYear: '2023',
            trending: false,
            description: 'The 2023 Jeep Wrangler is built for rugged terrain and off-road adventures. It’s a durable, high-performing SUV that guarantees excitement.',
            acceleration: '0-60 mph in 6.8 seconds',
            engineSize: '3.6L V6',
            electric: false,
            horsePower: '285 hp',
            profileName: 'Tunde',
            reviewStore: 4.8,
            comments: ['Rugged and high-performing', 'Great for off-road adventures'],
            yearsSpent: 3
        },
        {
            id:58,
            name: 'Hyundai Sonata',
            path: 'https://th.bing.com/th/id/OIP.DHILS33qT3wuN_WKtZVXegHaEn?w=279&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 13000,
            category: 'Sedan',
            state: 'Ibadan',
            country: 'Nigeria',
            manufactureYear: '2021',
            trending: false,
            description: 'The 2021 Hyundai Sonata combines stylish looks with reliable performance. It’s the perfect mid-size sedan for daily drives and family outings.',
            acceleration: '0-60 mph in 7.8 seconds',
            engineSize: '2.5L 4-cylinder',
            electric: false,
            horsePower: '191 hp',
            profileName: 'Olubunmi',
            reviewStore: 4.5,
            comments: ['Stylish and reliable', 'Great for daily drives'],
            yearsSpent: 1
        },
        {
            id:59,
            name: 'Toyota Highlander',
            path: 'https://th.bing.com/th/id/OIP.GN-KrqsXln_jv8S3j0rpqwHaFF?w=248&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 18000,
            category: 'SUV',
            state: 'Port Harcourt',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: false,
            description: 'The 2022 Toyota Highlander is a spacious and reliable SUV. With advanced safety features and a smooth ride, it’s great for family trips.',
            acceleration: '0-60 mph in 7.2 seconds',
            engineSize: '3.5L V6',
            electric: false,
            horsePower: '295 hp',
            profileName: 'Ifeanyi',
            reviewStore: 4.7,
            comments: ['Spacious and reliable', 'Great for family trips'],
            yearsSpent: 2
        },
        {
            id:60,
            name: 'Chevrolet Malibu',
            path: 'https://th.bing.com/th?id=OIF.crm%2fVEUBf2n6XipRSN7O3g&w=291&h=194&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 12500,
            category: 'Sedan',
            state: 'Enugu',
            country: 'Nigeria',
            manufactureYear: '2020',
            trending: false,
            description: 'The 2020 Chevrolet Malibu offers a comfortable ride and a sleek design. It’s an affordable option for both short and long-distance drives.',
            acceleration: '0-60 mph in 8.5 seconds',
            engineSize: '1.5L Turbo 4-cylinder',
            electric: false,
            horsePower: '160 hp',
            profileName: 'Chinwe',
            reviewStore: 4.5,
            comments: ['Comfortable ride', 'Sleek design'],
            yearsSpent: 1
        },
        {
            id:61,
            name: 'Lexus RX 350',
            path: 'https://th.bing.com/th/id/OIP.Z0eKCEGuhIdxnmPPNNK36AHaFj?w=263&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 28000,
            category: 'Luxury Cars',
            state: 'Lagos',
            country: 'Nigeria',
            manufactureYear: '2023',
            trending: false,
            description: 'The 2023 Lexus RX 350 is a luxurious SUV with excellent performance and comfort. A great choice for anyone looking to travel in style.',
            acceleration: '0-60 mph in 7.7 seconds',
            engineSize: '3.5L V6',
            electric: false,
            horsePower: '295 hp',
            profileName: 'Temidayo',
            reviewStore: 4.8,
            comments: ['Luxurious and comfortable', 'Great performance'],
            yearsSpent: 1
        },
        {
            id:62,
            name: 'Tesla Model Y',
            path: 'https://th.bing.com/th/id/OIP.Mur8yoAiAm_Rk8Gtto6yDAHaEK?w=283&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 22000,
            category: 'Electric Cars',
            state: 'Abuja',
            country: 'Nigeria',
            manufactureYear: '2023',
            trending: false,
            description: 'The 2023 Tesla Model Y is an all-electric SUV that combines cutting-edge technology with exceptional performance. Ideal for eco-conscious drivers.',
            acceleration: '0-60 mph in 4.8 seconds',
            engineSize: 'Electric Motor',
            electric: true,
            horsePower: '384 hp',
            profileName: 'Chukwudi',
            reviewStore: 4.9,
            comments: ['Cutting-edge technology', 'Exceptional performance'],
            yearsSpent: 1
        },
        {
            id:63,
            name: 'Ford Explorer',
            path: 'https://th.bing.com/th/id/OIP.ReKiSWxL8e0j9uoDFBGrjwHaEK?w=321&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 17000,
            category: 'SUV',
            state: 'Abuja',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: false,
            description: 'This Ford Explorer has been my trusty companion on countless adventures. It’s spacious, powerful, and makes every trip enjoyable. You’ll love it for road trips!',
            acceleration: '0-60 mph in 6.8 seconds',
            engineSize: '3.0L V6',
            electric: false,
            horsePower: '400 hp',
            profileName: 'Adeola',
            reviewStore: 4.7,
            comments: ['Spacious and powerful', 'Great for road trips'],
            yearsSpent: 2
        },
        {
            id:64,
            name: 'Honda Civic',
            path: 'https://th.bing.com/th/id/OIP.48xRo3n5LWIMhqDcTgQcKAHaE7?w=247&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 11000,
            category: 'Sedan',
            state: 'Lagos',
            country: 'Nigeria',
            manufactureYear: '2021',
            trending: false,
            description: 'My 2021 Honda Civic has been the perfect car for daily commutes. It’s reliable, fuel-efficient, and has a sleek design that always turns heads.',
            acceleration: '0-60 mph in 8.2 seconds',
            engineSize: '2.0L 4-cylinder',
            electric: false,
            horsePower: '158 hp',
            profileName: 'Nneka',
            reviewStore: 4.6,
            comments: ['Reliable and fuel-efficient', 'Sleek design'],
            yearsSpent: 1
        },
        {
            id:65,
            name: 'Toyota Camry',
            path: 'https://th.bing.com/th/id/OIP.FntotHBxoN3wokbDfcCn1gHaE8?w=268&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 13500,
            category: 'Sedan',
            state: 'Ibadan',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: false,
            description: 'This Camry is a gem! It’s smooth, stylish, and incredibly comfortable. It’s my go-to for everything from quick errands to long drives.',
            acceleration: '0-60 mph in 7.4 seconds',
            engineSize: '2.5L 4-cylinder',
            electric: false,
            horsePower: '203 hp',
            profileName: 'Titi',
            reviewStore: 4.7,
            comments: ['Smooth and stylish', 'Incredibly comfortable'],
            yearsSpent: 1
        },
        {
            id:66,
            name: 'Nissan Altima',
            path: 'https://th.bing.com/th/id/OIP.7SbqWOBBGvH4co-ezB3ZqAHaEK?w=275&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 12000,
            category: 'Sedan',
            state: 'Kano',
            country: 'Nigeria',
            manufactureYear: '2020',
            trending: false,
            description: 'I’ve enjoyed every moment with my Altima. It’s stylish, reliable, and has enough space for road trips with friends or family.',
            acceleration: '0-60 mph in 8.0 seconds',
            engineSize: '2.5L 4-cylinder',
            electric: false,
            horsePower: '188 hp',
            profileName: 'Zainab',
            reviewStore: 4.5,
            comments: ['Stylish and reliable', 'Great for road trips'],
            yearsSpent: 1
        },
        {
            id:67,
            name: 'Chevrolet Tahoe',
            path: 'https://th.bing.com/th/id/OIP.SSe1aOEuB1VWYtnAeo9xiwHaEK?w=322&h=181&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 20000,
            category: 'SUV',
            state: 'Lagos',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: false,
            description: 'The Chevy Tahoe is a beast! I love how it handles tough terrain and carries everything I need. It’s perfect for big groups or lots of gear.',
            acceleration: '0-60 mph in 7.1 seconds',
            engineSize: '5.3L V8',
            electric: false,
            horsePower: '355 hp',
            profileName: 'Kehinde',
            reviewStore: 4.8,
            comments: ['Handles tough terrain', 'Perfect for big groups'],
            yearsSpent: 2
        },
       
       
        {
            id:68,
            name: 'Kia Sportage',
            path: 'https://th.bing.com/th/id/OIP.mtfmOPAb6yHmY1rkDkT7SgHaEA?w=298&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 14000,
            category: 'Compact Cars',
            state: 'Enugu',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: false,
            description: 'My Kia Sportage is a joy to drive. It’s perfect for city trips and weekend getaways, with a great balance of style and functionality.',
            acceleration: '0-60 mph in 8.6 seconds',
            engineSize: '2.4L 4-cylinder',
            electric: false,
            horsePower: '181 hp',
            profileName: 'Enugu Rides',
            reviewScore: 4.5,
            comments: [
                'Smooth ride and excellent fuel efficiency!',
                'Perfect for a weekend getaway, loved it.',
            ],
            yearsOnApp: 3
        },
        {
            id:69,
            name: 'Volkswagen Tiguan',
            path: 'https://th.bing.com/th/id/OIP.xWCzETjvhzxtryErcOsE2QHaD9?w=239&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 15000,
            category: 'SUV',
            state: 'Benin',
            country: 'Nigeria',
            manufactureYear: '2021',
            trending: false,
            description: 'This Tiguan is a family favorite. It’s reliable, comfortable, and packed with features to make every trip enjoyable.',
            acceleration: '0-60 mph in 9.1 seconds',
            engineSize: '2.0L Turbo 4-cylinder',
            electric: false,
            horsePower: '184 hp',
            profileName: 'Benin Motors',
            reviewScore: 4.7,
            comments: [
                'Very spacious and comfortable for family trips.',
                'The handling was superb, great experience!',
            ],
            yearsOnApp: 5
        },
        {
            id:70,
            name: 'Mercedes-Benz C-Class',
            path: 'https://th.bing.com/th/id/OIP.lfmVVLMio1Kph8SKDdnFkAHaEK?w=229&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 24000,
            category: 'Luxury Cars',
            state: 'Lagos',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: false,
            description: 'My C-Class is all about luxury and performance. It’s a fantastic car for anyone who wants a premium driving experience.',
            acceleration: '0-60 mph in 5.7 seconds',
            engineSize: '2.0L Turbo 4-cylinder',
            electric: false,
            horsePower: '255 hp',
            profileName: 'Lagos Luxury Rentals',
            reviewScore: 4.9,
            comments: [
                'Incredible luxury and smooth performance!',
                'The car made my trip feel first-class.',
            ],
            yearsOnApp: 4
        },
        {
            id:71,
            name: 'Chevrolet Silverado',
            path: 'https://m.atcdn.co.uk/ect/media/b9218018278a4b5da08f4ebce7f973da.jpg',
            rentalPricePerDay: 15000,
            category: 'Pickup Trucks',
            state: 'Abuja',
            country: 'Nigeria',
            manufactureYear: '2021',
            trending: false,
            description: 'This Silverado is built tough for work and play. Perfect for hauling cargo or hitting the open road.',
            acceleration: '0-60 mph in 7.0 seconds',
            engineSize: '5.3L V8',
            electric: false,
            horsePower: '355 hp',
            profileName: 'Abuja Auto Rentals',
            reviewScore: 4.6,
            comments: [
                'Great for moving heavy loads with ease!',
                'The truck is a powerhouse and very reliable.',
            ],
            yearsOnApp: 2
        },
        {
            id:72,
            name: 'Toyota RAV4',
            path: 'https://th.bing.com/th/id/OIP.1WpNuROW8eID9Ydfqc16IgHaE8?w=273&h=182&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 12000,
            category: 'Compact Cars',
            state: 'Ibadan',
            country: 'Nigeria',
            manufactureYear: '2020',
            trending: false,
            description: 'The RAV4 offers excellent fuel efficiency and plenty of space. Ideal for family trips or daily commutes.',
            acceleration: '0-60 mph in 8.4 seconds',
            engineSize: '2.5L 4-cylinder',
            electric: false,
            horsePower: '203 hp',
            profileName: 'Ibadan Drives',
            reviewScore: 4.5,
            comments: [
                'Super comfortable and very economical!',
                'Had a great trip with this reliable SUV.',
            ],
            yearsOnApp: 3
        },
        {
            id:73,
            name: 'Tesla Model Y',
            path: 'https://th.bing.com/th/id/OIP.bFGFuca02j7k2oyOxjFMgAHaEK?w=302&h=180&c=7&r=0&o=5&dpr=1.3&pid=1.7',
            rentalPricePerDay: 25000,
            category: 'Electric Cars',
            state: 'Lagos',
            country: 'Nigeria',
            manufactureYear: '2022',
            trending: false,
            description: 'The Tesla Model Y is an electric marvel. Fast, efficient, and packed with cutting-edge technology.',
            acceleration: '0-60 mph in 4.8 seconds',
            engineSize: 'Dual Electric Motors',
            electric: true,
            horsePower: '384 hp',
            profileName: 'Green Lagos Rentals',
            reviewScore: 4.9,
            comments: [
                'Amazing acceleration and futuristic features!',
                'Loved the autopilot feature, very smooth ride.',
            ],
            yearsOnApp: 1
        }

    ])

    return(
        <AppContext.Provider value={{ carCategories, setCarCategories,carListings,setCarListings,form,setForm,isLoggedIn,setIsLoggedIn,CurrentCategory,setCurrentCategory,detailsIndex,setDetailsIndex }}>
            {children}
        </AppContext.Provider>
    )

}

export {AppContext,AppProvider}